
name: Build and Deploy on Local VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull and run container
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/node-docker-cicd:latest
          docker stop node-app || true
          docker rm node-app || true
          docker run -d \
            --name node-app \
            -p 8080:3000 \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/node-docker-cicd:latest
